######################################################################
# Automatically generated by qmake (2.01a) Tue Jan 8 10:02:49 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
LIBS += -lvlc

# Input
HEADERS += Player.hpp Screens.hpp Mixer.hpp Calibrator.hpp View.hpp Controller.hpp Model.hpp symbols.hpp
SOURCES += main.cpp Player.cpp Screens.cpp Mixer.cpp Calibrator.cpp View.cpp Controller.cpp Model.cpp
