#############################################################################
# Makefile for building: cheapDistanceMeteringSystem
# Generated by qmake (2.01a) (Qt 4.8.1) on: Sun Apr 14 17:19:56 2013
# Project:  cheapDistanceMeteringSystem.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile cheapDistanceMeteringSystem.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/i386-linux-gnu -lvlc -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		Player.cpp \
		Screens.cpp \
		Mixer.cpp \
		Calibrator.cpp \
		View.cpp \
		Controller.cpp \
		Model.cpp moc_Controller.cpp
OBJECTS       = main.o \
		Player.o \
		Screens.o \
		Mixer.o \
		Calibrator.o \
		View.o \
		Controller.o \
		Model.o \
		moc_Controller.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		cheapDistanceMeteringSystem.pro
QMAKE_TARGET  = cheapDistanceMeteringSystem
DESTDIR       = 
TARGET        = cheapDistanceMeteringSystem

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: cheapDistanceMeteringSystem.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/i386-linux-gnu/libQtGui.prl \
		/usr/lib/i386-linux-gnu/libQtCore.prl
	$(QMAKE) -o Makefile cheapDistanceMeteringSystem.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/i386-linux-gnu/libQtGui.prl:
/usr/lib/i386-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile cheapDistanceMeteringSystem.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/cheapDistanceMeteringSystem1.0.0 || $(MKDIR) .tmp/cheapDistanceMeteringSystem1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/cheapDistanceMeteringSystem1.0.0/ && $(COPY_FILE) --parents Player.hpp Screens.hpp Mixer.hpp Calibrator.hpp View.hpp Controller.hpp Model.hpp symbols.hpp .tmp/cheapDistanceMeteringSystem1.0.0/ && $(COPY_FILE) --parents main.cpp Player.cpp Screens.cpp Mixer.cpp Calibrator.cpp View.cpp Controller.cpp Model.cpp .tmp/cheapDistanceMeteringSystem1.0.0/ && (cd `dirname .tmp/cheapDistanceMeteringSystem1.0.0` && $(TAR) cheapDistanceMeteringSystem1.0.0.tar cheapDistanceMeteringSystem1.0.0 && $(COMPRESS) cheapDistanceMeteringSystem1.0.0.tar) && $(MOVE) `dirname .tmp/cheapDistanceMeteringSystem1.0.0`/cheapDistanceMeteringSystem1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/cheapDistanceMeteringSystem1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_Controller.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_Controller.cpp
moc_Controller.cpp: Calibrator.hpp \
		symbols.hpp \
		Mixer.hpp \
		Screens.hpp \
		Model.hpp \
		Controller.hpp
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) Controller.hpp -o moc_Controller.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

main.o: main.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

Player.o: Player.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Player.o Player.cpp

Screens.o: Screens.cpp Screens.hpp \
		symbols.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Screens.o Screens.cpp

Mixer.o: Mixer.cpp Mixer.hpp \
		symbols.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Mixer.o Mixer.cpp

Calibrator.o: Calibrator.cpp Calibrator.hpp \
		symbols.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Calibrator.o Calibrator.cpp

View.o: View.cpp View.hpp \
		Calibrator.hpp \
		symbols.hpp \
		Mixer.hpp \
		Screens.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o View.o View.cpp

Controller.o: Controller.cpp Controller.hpp \
		Calibrator.hpp \
		symbols.hpp \
		Mixer.hpp \
		Screens.hpp \
		Model.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Controller.o Controller.cpp

Model.o: Model.cpp Model.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Model.o Model.cpp

moc_Controller.o: moc_Controller.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Controller.o moc_Controller.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

